export default {
  Fiber: 'Fiber',
  Wood: 'Wood',
  Stone: 'Stone',
  'Rupu Vine': 'Rupu Vine',
  Cotton: 'Cotton',
  Cattail: 'Cattail',
  'Redwood Wood': 'Redwood Wood',
  Bone: 'Bone',
  'Mushroom Flesh': 'Mushroom Flesh',
  Phemkey: 'Phemkey',
  Nurr: 'Nurr',
  Crab: 'Crab',
  Ash: 'Ash',
  'Burnt Tree': 'Burnt Tree',
  'Burnt Bush': 'Burnt Bush',
  'Aloe Vera': 'Aloe Vera',
  'Volcanic Plant': 'Volcanic Plant',
  Corn: 'Corn',
  Driftwood: 'Driftwood',
  Obsidian: 'Obsidian',
  Lava: 'Lava',
  Clay: 'Clay'
}
